const GUNTUR_LOCATIONS = [
  'Adavitakkellapadu',
  'Ahmad Nagar',
  'Ali Nagar',
  'Anandapet',
  'Ankireddypalem',
  'Annapurna Nagar',
  'APHB Colony',
  'Arundathi Nagar',
  'Arundelpet',
  'Ashok Nagar',
  'Auto Nagar',
  'Balaji Nagar',
  'Brindavan Gardens',
  'Brodipet',
  'Budampadu',
  'Chandramouli Nagar',
  'Chinapalakaluru',
  'Christian Pet',
  'Chowdavaram',
  'Chowtra',
  'Dasupalem',
  'Donka Road',
  'Dwaraka Nagar',
  'Etukuru',
  'Fathima Puram',
  'Gandhi Nagar',
  'Gorantla',
  'Guntur Vari Thota',
  'Israel Pet',
  'JKC Nagar',
  'Kanna Vari Thota',
  'Kothapet',
  'Koritepadu',
  'Krishna Tulasi Nagar',
  'Lakshmipuram',
  'Lalapet',
  'LB Nagar',
  'LIC Colony',
  'Maddirala Colony',
  'Mission Form',
  'Naidupet',
  'Nallapadu',
  'Navabharath Nagar',
  'Nehru Nagar',
  'NGO Colony',
  'Old Guntur',
  'Panduranga Nagar',
  'Pattabhipuram',
  'Pedapalakaluru',
  'Pothuru',
  'Prakash Nagar',
  'Pragathi Nagar',
  'Railpet',
  'Rami Reddy Thota',
  'Ratnagiri Colony',
  'Reddypalem',
  'RTC Colony',
  'Saibaba Colony',
  'Sambasiva Pet',
  'Sangadigunta',
  'Sarada Colony',
  'Seetha Nagar',
  'Srinivasa Nagar Colony',
  'Sri Ram Nagar',
  'SVN Colony',
  'Swarnabharathi Nagar',
  'Syamala Nagar',
  'Taraka Rama Nagar',
  'Telecom Nagar',
  'Vasavi Nagar',
  'Vidya Nagar',
  'Vikas Nagar',
  'Vinoba Nagar',
] as const;

const VIJAYAWADA_LOCATIONS = [
  'Ajit Singh Nagar',
  'Andhra Ratna Road',
  'Arundelpet',
  'Ashok Nagar',
  'Auto Nagar',
  'Ayyappa Nagar',
  'Bank Colony',
  'Benz Circle',
  'Bhavanipuram',
  'BR Nagar',
  'Chitti Nagar',
  'Christurajupuram',
  'Currency Nagar',
  'Devi Nagar',
  'Durga Agraharam',
  'Enikepadu',
  'Gandhi Nagar',
  'Ganguru',
  'Gollapudi',
  'Governorpet',
  'Gunadala',
  'Guru Nanak Colony',
  'Hanumanpet',
  'Ibrahimpatnam',
  'Islampet',
  'Jakkampudi',
  'Kanuru',
  'Kedareswarapeta',
  'Krishna Lanka',
  'Labbipet',
  'Machavaram',
  'Madhura Nagar',
  'Milk Colony',
  'Moghalrajpuram',
  'Mutyalampadu',
  'New Postal Colony',
  'New Rajarajeswaripeta',
  'Nunna',
  'One Town',
  'Patamata',
  'Patamata Lanka',
  'Payakapuram',
  'Poranki',
  'Prasadampadu',
  'Ramachandra Nagar',
  'Ramalingeswara Nagar',
  'Ranigarithota',
  'Satyanarayanapuram',
  'Singh Nagar',
  'Sri Nagar Colony',
  'Suryaraopet',
  'Tarapet',
  'Vambay Colony',
  'Vidhyadharapuram',
  'Vinchipet',
  'Yanamalakuduru',
] as const;

export const SERVICE_LOCATION_NAMES_BY_CITY = {
  Guntur: GUNTUR_LOCATIONS,
  Vijayawada: VIJAYAWADA_LOCATIONS,
} as const;

export type ServiceCity = keyof typeof SERVICE_LOCATION_NAMES_BY_CITY;
export const SERVICE_LOCATION_NAMES = Object.values(
  SERVICE_LOCATION_NAMES_BY_CITY,
).flatMap((locations) => [...locations]);

const CITY_CENTRES: Record<ServiceCity, { lat: number; lng: number }> = {
  Guntur: { lat: 16.3067, lng: 80.4365 },
  Vijayawada: { lat: 16.5062, lng: 80.648 },
};

export function getServiceLocation(city: string, location: string) {
  const locations = SERVICE_LOCATION_NAMES_BY_CITY[city as ServiceCity];
  if (!locations || !(locations as readonly string[]).includes(location)) {
    return null;
  }
  // The locality is the dispatch boundary. Its city centre is only a fallback
  // coordinate until a technician shares a more precise live position.
  return CITY_CENTRES[city as ServiceCity];
}
