export const SERVICE_LOCATIONS = {
  Guntur: [
    "Adavitakkellapadu",
    "Ahmad Nagar",
    "Ali Nagar",
    "Anandapet",
    "Ankireddypalem",
    "Annapurna Nagar",
    "APHB Colony",
    "Arundathi Nagar",
    "Arundelpet",
    "Ashok Nagar",
    "Auto Nagar",
    "Balaji Nagar",
    "Brindavan Gardens",
    "Brodipet",
    "Budampadu",
    "Chandramouli Nagar",
    "Chinapalakaluru",
    "Christian Pet",
    "Chowdavaram",
    "Chowtra",
    "Dasupalem",
    "Donka Road",
    "Dwaraka Nagar",
    "Etukuru",
    "Fathima Puram",
    "Gandhi Nagar",
    "Gorantla",
    "Guntur Vari Thota",
    "Israel Pet",
    "JKC Nagar",
    "Kanna Vari Thota",
    "Kothapet",
    "Koritepadu",
    "Krishna Tulasi Nagar",
    "Lakshmipuram",
    "Lalapet",
    "LB Nagar",
    "LIC Colony",
    "Maddirala Colony",
    "Mission Form",
    "Naidupet",
    "Nallapadu",
    "Navabharath Nagar",
    "Nehru Nagar",
    "NGO Colony",
    "Old Guntur",
    "Panduranga Nagar",
    "Pattabhipuram",
    "Pedapalakaluru",
    "Pothuru",
    "Prakash Nagar",
    "Pragathi Nagar",
    "Railpet",
    "Rami Reddy Thota",
    "Ratnagiri Colony",
    "Reddypalem",
    "RTC Colony",
    "Saibaba Colony",
    "Sambasiva Pet",
    "Sangadigunta",
    "Sarada Colony",
    "Seetha Nagar",
    "Srinivasa Nagar Colony",
    "Sri Ram Nagar",
    "SVN Colony",
    "Swarnabharathi Nagar",
    "Syamala Nagar",
    "Taraka Rama Nagar",
    "Telecom Nagar",
    "Vasavi Nagar",
    "Vidya Nagar",
    "Vikas Nagar",
    "Vinoba Nagar",
  ],
  Vijayawada: [
    "Ajit Singh Nagar",
    "Andhra Ratna Road",
    "Arundelpet",
    "Ashok Nagar",
    "Auto Nagar",
    "Ayyappa Nagar",
    "Bank Colony",
    "Benz Circle",
    "Bhavanipuram",
    "BR Nagar",
    "Chitti Nagar",
    "Christurajupuram",
    "Currency Nagar",
    "Devi Nagar",
    "Durga Agraharam",
    "Enikepadu",
    "Gandhi Nagar",
    "Ganguru",
    "Gollapudi",
    "Governorpet",
    "Gunadala",
    "Guru Nanak Colony",
    "Hanumanpet",
    "Ibrahimpatnam",
    "Islampet",
    "Jakkampudi",
    "Kanuru",
    "Kedareswarapeta",
    "Krishna Lanka",
    "Labbipet",
    "Machavaram",
    "Madhura Nagar",
    "Milk Colony",
    "Moghalrajpuram",
    "Mutyalampadu",
    "New Postal Colony",
    "New Rajarajeswaripeta",
    "Nunna",
    "One Town",
    "Patamata",
    "Patamata Lanka",
    "Payakapuram",
    "Poranki",
    "Prasadampadu",
    "Ramachandra Nagar",
    "Ramalingeswara Nagar",
    "Ranigarithota",
    "Satyanarayanapuram",
    "Singh Nagar",
    "Sri Nagar Colony",
    "Suryaraopet",
    "Tarapet",
    "Vambay Colony",
    "Vidhyadharapuram",
    "Vinchipet",
    "Yanamalakuduru",
  ],
} as const;

export type ServiceCity = keyof typeof SERVICE_LOCATIONS;
export const CITY_OPTIONS = Object.keys(SERVICE_LOCATIONS) as ServiceCity[];

export function locationsForCity(city: string): readonly string[] {
  return SERVICE_LOCATIONS[city as ServiceCity] ?? [];
}
